### ISSUE TITLE
Make 'god' globally accessible

### ISSUE THREAD

**Issue by sourishsarmah** [BugHoppers/gods_eye#1]
* Make the command accessible from all directories.

**Comment by nityanandagohain** [comment]
we can make it installable via pip or  I think if add the executable to PATH then it will work.

**Comment by sourishsarmah** [comment]
I have sent a Pull request for searching the config file in the PATH directories.
But there is no script to automate the task of adding the directory to the PATH variable. Can you make one @nityanandagohain ?

**Comment by AdirthaBorgohain** [comment]
Doesn't #13 resolve this issue?

**Comment by AdirthaBorgohain** [comment]
Closing this as this is resolved.
