### ISSUE TITLE
Increase the brightness of the screen while using web cam

### ISSUE THREAD

**Issue by sourishsarmah** [BugHoppers/gods_eye#19]
In low light condition, the webcam can't recognize faces.
Make a funtuon that 
* reads the current brightness and stores it.
* changes screen brightness to 100%.
* restores original brightness

**Comment by sourishsarmah** [comment]
The feature - increasing brightness of the screen for better lighting while facial authentication is added only for gnome environments.

**Comment by AdirthaBorgohain** [comment]
Issue resolved. Closing Issue.
