### ISSUE TITLE
Migrate from pycrypto to pycryptodome

### ISSUE THREAD

**Issue by AdirthaBorgohain** [BugHoppers/gods_eye#23]
Pycrypto has been found to have some vulnerabilities. Pycryptodome is said to be its direct replacement. There's not much difference between the both in its implementation. The project needs to be migrated to it.

**Comment by nityanandagohain** [comment]
Please fix this @AdirthaBorgohain

**Comment by AdirthaBorgohain** [comment]
Closing this. #29 is the relevant commit for this issue.
