### ISSUE TITLE
Generate unique key for each user

### ISSUE THREAD

**Issue by AdirthaBorgohain** [BugHoppers/gods_eye#9]
At the moment, a hardcoded common key is being used for encryption and decryption. We need to generate different unique keys while setting up gods eye for the first time.

**Comment by DPS0340** [comment]
can be readed and writed by file? i'm thinking about json store.

**Comment by DPS0340** [comment]
if it's right. there will be fast.

**Comment by DPS0340** [comment]
#11

**Comment by AdirthaBorgohain** [comment]
Yes. You can generate a random 32 byte key and store it in the .god folder that is created in the home directory. Whenever encryption or decryption is needed, that key file can be read and used accordingly. Would you be working on it?

**Comment by DPS0340** [comment]
yup. just dump byte file. and load this file later. it just works.

**Comment by AdirthaBorgohain** [comment]
Make the changes and commit when you can. Will test out on my system.

**Comment by DPS0340** [comment]
please look #11

**Comment by AdirthaBorgohain** [comment]
Issue resolved. Closing it.
